# Generated by Django 3.2.6 on 2021-08-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irradiance', '0002_auto_20210806_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Montsum2020_02',
        ),
    ]
